application:

  # Project name
  name: vanpattenmedia

  # Path to a repo for Capistrano
  repo: git://github.com/username/repo.com.git

  # User on your server who will be executing the deployment
  deploy_user: deploy

  # Users on your server who can access this project - be sure to include your deploy_user!
  access_users: [deploy, user1, user2, user3]

  # User/group on your server who will own this project
  user: user
  group: group

  # The name of the theme
  theme: theme

  # Domain for this project, no www. or subdomains
  domain: domain.com

  tbl_prefix: wp_
  # The database prefix for WordPress

  servers:
  # The server addresses and SSH details for each stage.

    dev:
      # Vagrant default settings
      ip: 127.0.0.1
      port: 2222
      user: vagrant

    staging:
    # Replace these with your server's IP, deploy user and SSH port
      ip: 0.0.0.0
      port: 0
      user: deploy

    production:
      ip: 0.0.0.0
      port: 0
      user: deploy

 
